<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="3.132" timestamp="2023-11-02T12:22:44.800117" hostname="LAPTOP-6MBQHUB0"><testcase classname="" name="test.unit.calc_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\guskl\Desktop\maestriaunir\cuatrimestre dos\entornos de integracion y entrega continua\deber2\unir-test\unir-test\test\unit\calc_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
unit\calc_test.py:5: in &lt;module&gt;
    from app.calc import Calculator
E   ModuleNotFoundError: No module named 'app'</error></testcase><testcase classname="" name="test.unit.util_test" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\guskl\Desktop\maestriaunir\cuatrimestre dos\entornos de integracion y entrega continua\deber2\unir-test\unir-test\test\unit\util_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
unit\util_test.py:4: in &lt;module&gt;
    from app import util
E   ModuleNotFoundError: No module named 'app'</error></testcase></testsuite></testsuites>